#!/user/bin/env python

import os

myfilename = "housing.data.txt"

#if os.path.isfile(myfilename):
#	print("yay I have a file")
#else:
#	print("boo no file for me")
#
with open(myfilename, 'r') as file_handle:
	for line in file_handle.readlines():
		line_clean = line.replace('   ', ' ').replace('  ', ' ')
		values = line_clean.strip()
		print(values)		
	        for value in values:
			print(float(value))
	

